# --------------------------
# English language
# --------------------------
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 1


# --------------------------
# Spanish language
# --------------------------
[es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content"
weight = 2