
# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

#################### default parameters ################################
[params]
# Meta data
description = "Blog de la Asociación Chilena de Estudios del Trabajo"
author = "Taller Los Ojos"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2
content = "Este sitio utiliza cookies. Al continuar usándolo, acepta su uso."
button = "Acepto"

# banner
[params.banner]
heading = "Asociación Chilena de Estudios del Trabajo"
image = "https://www.memoriasdelsigloxx.cl/601/articles-64403_imagen.jpg"

# blog
[params.blog]
heading = "cómo los cambios económicos, tecnológicos y demográficos afectan a la fuerza de trabajo y a las estructuras de poder."

# call to action
[params.call_to_action]
enable = true
title = "Contact us for more information."
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact/"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"



# footer
[params.footer]
title = "Este blog"
content = "Realizar, auspiciar, promover y asesorar todo tipo de estudios, proyectos y programas de carácter cultural. Apoyar la promoción y desarrollo de actividades culturales, a través de trabajos, estudios, intercambio de tecnologías, cursos de perfeccionamiento de profesores, alumnos o personas interesadas en la expresión de la cultura.<br><br><br><small><b> Imagen de portada: </b>Temporeras de Gualliguaica- memoriasdelsigloxx.cl</small>"
address = "+56 9 8357 3198 <br> contacto@achetchile.cl <br> <br><b>Formulario 1er Congreso Chileno de Estudios del Trabajo </b> <br>https://forms.gle/VfDh1mF9w38QmyVw5"
# hours = ""
copyright = "Asociación Chilena de Estudios del Trabajo &copy; 2025 "

############################# social site ########################
[params.social]
yelp = ""
facebook = ""
twitter = ""
instagram = ""
email = ""
linkedin = ""

languageCode = "es-es"
defaultContentLanguage = "es-es"
